[package]
name = "frame-benchmarking-cli"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "CLI for benchmarking FRAME"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
rand = { version = "0.8.4", features = ["small_rng"] }
frame-benchmarking = { version = "4.0.0-dev", path = "../../../frame/benchmarking" }
frame-support = { version = "4.0.0-dev", path = "../../../frame/support" }
sp-core = { version = "5.0.0", path = "../../../primitives/core" }
sc-service = { version = "0.10.0-dev", default-features = false, path = "../../../client/service" }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api" }
sc-cli = { version = "0.10.0-dev", path = "../../../client/cli" }
sc-client-db = { version = "0.10.0-dev", path = "../../../client/db" }
sc-executor = { version = "0.10.0-dev", path = "../../../client/executor" }
sp-externalities = { version = "0.11.0", path = "../../../primitives/externalities" }
sp-database = { version = "4.0.0-dev", path = "../../../primitives/database" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
sp-keystore = { version = "0.11.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "5.0.0", path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.11.0", path = "../../../primitives/state-machine" }
codec = { version = "2.0.0", package = "parity-scale-codec" }
clap = { version = "3.0", features = ["derive"] }
chrono = "0.4"
serde = "1.0.132"
serde_json = "1.0.74"
handlebars = "4.1.6"
Inflector = "0.11.4"
linked-hash-map = "0.5.4"
log = "0.4.8"
itertools = "0.10.3"

[features]
default = ["db"]
db = ["sc-client-db/with-kvdb-rocksdb", "sc-client-db/with-parity-db",
# For in-memory DB.
"sc-client-db/test-helpers"]
